name: publish-pypi-deploy

on:
  release:
    types: [ published ]
  # pull_request:
  #   branches: [ main ]

jobs:

  build:
    name: Build the package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/types-pydicom/
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Build package
      run: |
        python -m pip install -U pip
        python -m pip install build
        python -m build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist/

    - name: Publish package to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
